language: node_js
node_js:
  - '10'

script:
- echo "npm test temporarily disabled"
before_deploy:
  - sed -i -- 's/openWindow("\/")/openWindow("\/try-scheduled-push")/' ./src/sw.js
  - cp -rf ./src ./public/
  - echo '' > ./public/.nojekyll
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_GH
  local-dir: ./public
  on:
    branch: master
