language: node_js
node_js:
  - '10'

before_deploy:
  - cp -rf ./src ./public/
  - echo '' > ./public/.nojekyll
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_GH
  local-dir: ./public
  on:
    branch: master
